# Generated by Django 5.0.4 on 2024-05-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='data_published',
            field=models.DateTimeField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posts',
            name='text_post',
            field=models.TextField(default='NONE TEXT'),
            preserve_default=False,
        ),
    ]
