# Generated by Django 5.0.4 on 2024-06-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_category_posts_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='author',
            field=models.CharField(default='admin', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='posts',
            name='data_published',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
