# Generated by Django 5.0.4 on 2024-06-25 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Array_Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_post', models.IntegerField()),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
