# Generated by Django 5.0.4 on 2024-06-25 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_array_like_delete_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='array_like',
            old_name='value',
            new_name='id_user',
        ),
    ]
