# Generated by Django 5.1.2 on 2024-10-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_remove_posts_category_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='image',
            field=models.ImageField(blank=True, upload_to='photos_buy_to_sell'),
        ),
    ]
