# Generated by Django 5.1.2 on 2024-10-19 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_posts_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='pars_files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('format', models.CharField(max_length=10)),
                ('hash_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Whitelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files_format', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(blank=True, upload_to='photos_forum'),
        ),
    ]
