# Generated by Django 5.1.2 on 2024-10-19 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_pars_files_whitelist_alter_posts_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.pars_files'),
        ),
    ]
