# Generated by Django 5.1.2 on 2024-10-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_remove_posts_image_pars_files_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pars_files',
            name='name',
            field=models.FileField(blank=True, upload_to='photos_forum'),
        ),
    ]
