# Generated by Django 5.1.2 on 2024-10-23 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0013_alter_pars_files_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pars_files',
            old_name='name',
            new_name='file',
        ),
    ]
