# Generated by Django 5.1.2 on 2024-10-24 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0014_rename_name_pars_files_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pars_files',
            old_name='image',
            new_name='key_posts',
        ),
    ]
